movies/urls.py
from django.urls import path
from .views import CommentCreateView, movie_create, MovieListView, MovieUpdateView, MovieDeleteView, ReviewCreateView, movie_detail

app_name = 'movies'

urlpatterns = [
    path('', MovieListView.as_view(), name='movie-list'),
    path('create/', movie_create, name='movie-create'),
    path('<int:pk>', movie_detail, name='movie-detail'),
    path('<int:pk>/update', MovieUpdateView.as_view(), name='movie-update'),
    path('<int:pk>/delete', MovieDeleteView.as_view(), name='movie-delete'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment-create'),
    path('<int:pk>/review/', ReviewCreateView.as_view(), name='movie-review'),
]

yem_reviews/urls.py
from os import name
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, LogoutView, 
    PasswordResetConfirmView, PasswordResetView, 
    PasswordResetDoneView, PasswordResetCompleteView)

    
from django.urls import path, include
from movies.views import LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('movies/', include('movies.urls', namespace='movies')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('signup/', SignupView.as_view(), name='signup'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

movies/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    is_organisor = models.BooleanField(default=False)

class Movie(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=3000, default=" ")
    date_released = models.CharField(max_length=100)
    rating = models.IntegerField(default=0)
    reviews = models.IntegerField(default=0)
    poster = models.ImageField(default="default.jpeg", upload_to='movie_posters')

    def __str__(self):
	    return self.title

class Review(models.Model):
    title = models.ForeignKey(Movie, on_delete=CASCADE, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    details = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now) 

    def __str__(self):
    	return self.details

class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(default='')
    date_posted = models.DateTimeField(default=timezone.now) 

    def __str__(self):
	    return self.comment

movies/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField, PasswordResetForm
from .models import Movie, Review, Comment

User = get_user_model()

class MovieModelForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = (
            'title',
            'description',
            'date_released',
            'rating',
            'poster',
        )

class ReviewModelForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = (
            'title',
            'author',
            'details',
        )

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'review',
            'author',
            'comment',
        )

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}


movies/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.template import context
from django.views import generic
from .models import Movie, Review, Comment
from .forms import MovieModelForm, ReviewModelForm, CommentModelForm, CustomUserCreationForm


class SignupView(generic.CreateView):
	template_name = "registration/signup.html"
	form_class = CustomUserCreationForm

	def get_success_url(self):
		return reverse ("login")


class LandingPageView(generic.TemplateView):
	template_name = "landing.html"

class MovieListView(LoginRequiredMixin, generic.ListView):
	template_name = "leads/lead_list.html"
	queryset = Movie.objects.all()
	context_object_name = "movies"

def movie_create(request):
	if request.method == 'POST':
		print('Recieving a post request', request.FILES)


		# notice how I passed request.FILES. It is compulsory when you're receiving files

		# Your generic view function also works. I just want to show you how it would be written using just the 
		# normal function
		form = MovieModelForm(request.POST, request.FILES)
		if form.is_valid():
			print("The form is valid")
			print(form.cleaned_data)
			title = form.cleaned_data['title']
			date_released = form.cleaned_data['date_released']
			rating = form.cleaned_data['rating']
			poster = form.cleaned_data['poster']
			
			movie = Movie.objects.create(
				title=title,
				date_released=date_released,
				rating=rating,
				poster = poster
			)
			print(movie.poster.url)
		return redirect("/movies")	
	context = {
		"form": MovieModelForm()
	}
	return render(request, "movies/movie_create.html", context)



# class MovieCreateView(LoginRequiredMixin, generic.CreateView):
# 	template_name = "movies/movie_create.html"
# 	form_class  = MovieModelForm

# 	def get_success_url(self):
# 		return reverse ("movies:movie-list")

# 	def form_valid(self, form):
# 		# TODO send email
# 		send_mail(
# 			subject="A movie has been added to the list",
# 			message="Click the link below to see details of the movie",
# 			from_email="emekamba10@gmail.com",
# 			recipient_list=["admin@yemreviews.com"]
# 		)
		# return super(MovieCreateView, self).form_valid(form)


def movie_detail(request, pk):
	movies = Movie.objects.get(id=pk)
	reviews = Review.objects.filter(title=movies)
	comments = Comment.objects.all()
	context = {
        "movies": movies,
		"reviews": reviews,
		"comments": comments
    }
	return render(request, "movies/movie_detail.html", context)

class MovieUpdateView(LoginRequiredMixin, generic.UpdateView):
	template_name = "movies/movie_update.html"
	queryset = Movie.objects.all()
	form_class  = MovieModelForm

	def get_success_url(self):
		return reverse ("movies:movie-list")


class MovieDeleteView(LoginRequiredMixin, generic.DeleteView):
	template_name = "movies/movie_delete.html"
	queryset = Movie.objects.all()

	def get_success_url(self):
		return reverse ("movies:movie-list")

class ReviewCreateView(LoginRequiredMixin, generic.CreateView):
	template_name = "movies/review_create.html"
	form_class = ReviewModelForm

	def get_success_url(self):
		return reverse ("movies:movie-list")

class CommentCreateView(LoginRequiredMixin, generic.CreateView):
	template_name = "movies/comment_create.html"
	form_class = CommentModelForm

	def get_success_url(self):
		return reverse ("movies:movie-detail")

class LogoutView(generic.TemplateView):
	template_name = "logout.html"































































#--------------------------------------------------

# #def movie_create(request):
# 	if request.method == 'POST':
# 		print('Recieving a post request')
# 		form = MovieForm(request.POST)
# 		if form.is_valid():
# 			print("The form is valid")
# 			print(form.cleaned_data)
# 			title = form.cleaned_data['title']
# 			date_released = form.cleaned_data['date_released']
# 			rating = form.cleaned_data['rating']
			
# 			Movie.objects.create(
# 				title=title,
# 				date_released=date_released,
# 				rating=rating
# 			)
# 		return redirect("/movies")	
# 	context = {
# 		"form": MovieForm()
# 	}
# 	return render(request, "movies/movie_create.html", context)

# def movie_list(request):
# 	movies = Movie.objects.all()
# 	context = {
#         "movies": movies
#     }
# 	return render(request, "movies/movie_list.html", context)

# def movie_detail(request, pk):
# 	movies = Movie.objects.get(id=pk)
# 	reviews = Review.objects.filter(title=movies)
# 	context = {
#         "movies": movies,
# 		"reviews": reviews
#     }
# 	return render(request, "movies/movie_detail.html", context)

# def movie_create(request):
# 	if request.method == 'POST':
# 		print('Recieving a post request')
# 		form = MovieModelForm(request.POST)
# 		if form.is_valid():
# 			form.save()
# 		return redirect("/movies")	
# 	context = {
# 		"form": MovieModelForm()
# 	}
# 	return render(request, "movies/movie_create.html", context)

# def movie_update(request, pk):
# 	movie = Movie.objects.get(id=pk)
# 	form = MovieModelForm(instance=movie)
# 	if request.method == "POST":
# 		form = MovieModelForm(request.POST, instance=movie)
# 		if form.is_valid():
# 			form.save()
# 		return redirect("/movies")
# 	context = {
# 		"form": form,
# 		"movie": movie
# 	}
# 	return render(request, "movies/movie_update.html", context)

# def movie_delete(request, pk):
# 	movie = Movie.objects.get(id=pk)
# 	movie.delete()
# 	context = {
# 		"movie" : movie
# 	}
# 	return render(request, "movies/movie_delete.html", context)


# def landing_page(request):
# 	return render(request, "landing.html")

# def review_create(request, pk):
# 	movie = Movie.objects.get(id=pk)
# 	if request.method == 'POST':
# 		print('Recieving a post request')
# 		form = ReviewForm(request.POST)
# 		if form.is_valid():
# 			print("The form is valid")
# 			print(form.cleaned_data)
# 			movie.title = form.cleaned_data['title']
# 			author = form.cleaned_data['author']
# 			details = form.cleaned_data['details']
# 			Review.objects.create(
# 				title=movie.title,
# 				author=author,
# 				details=details
# 			)
# 		return redirect("/movies")	
# 	context = {
# 		"movie": movie,
# 		"form": ReviewForm()
# 	}
# 	return render(request, "movies/review_create.html", context)

# ----

# class ReviewDetailView(generic.DetailView):
# 	template_name = "movies/movie_detail.html"
# 	queryset = Review.objects.all()
# 	context_object_name = "reviews"

# # class CommentDetailView(generic.DetailView):
# # 	template_name = "movies/movie_detail.html"
# # 	queryset = Comment.objects.all()
# # 	context_object_name = "comments"

# def comment_list(request):
# 	comments = Comment.objects.all()
# 	context = {
#         "comments": comments
#     }
# 	return render(request, "movies/movie_detail.html", context)

movies/templates/movies/comment_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}



<h1 class="text-center">Add a Comment for: {{ review.details }}</h1>
    </head>
    <body>
        <a href="movies/movie_detail.html">Go back to {{ movie.title }}</a>
        <hr/>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit">
        </form>
    </body>
</html>

{% endblock content %}

movies/templates/movies/movie_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

        <a href="{% url 'movies:movie-list' %}">Go back to Movies</a>
       

    <!--  Movie Creation Form  -->

    <div class="flex w-full justify-center items-end">
        <div class="relative mr-4 lg:w-full xl:w-1/2 w-2/4 md:w-full text-left">
          <label for="hero-field" class="leading-7 text-sm text-gray-600">Add movie here</label>

<!-- You didn't add enctype="multipart/form-data" to <form>. It is needed to work with media files on django and all other platforms -->
<!-- else only text will be sent  -->

          <form class="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" value="Submit" class="inline-flex text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded text-lg">Submit</button>
        </form>
        </div> 
    </div>

 {% endblock content %}

movies/templates/movies/movie_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<h1 class="title-font sm:text-xl text-xl mb-4 text-center font-medium text-gray-900">Delete {{ movie.title }}</h1>
 
        <hr/>

    <!--  Delete Notification  -->

    <div class="w-full text-white bg-red-500">
        <div class="container flex items-center justify-between px-6 py-4 mx-auto">
            <div class="flex text-center">
                <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                    <path d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z"></path>
                </svg>

                <p class="mx-3 text-center">Are you sure you want to Delete {{ movie.title }}?</p>
            </div>
            <form class="" method="post">
                {% csrf_token %}
                {{ form|crispy}}
                <button type="submit" value="Submit" class="inline-flex text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded text-lg">Submit</button>
            </form>
            <a href="{% url 'movies:movie-list' %}"><button class="p-1 transition-colors duration-200 transform rounded-md hover:bg-opacity-25 hover:bg-gray-600 focus:outline-none">
                <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6 18L18 6M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            </button></a>
        </div>
    </div>
    <div class="flex container text-center w-full"> <a class="mx-auto hover:text-green-600" href="{% url 'movies:movie-list' %}">Go back to Movies</a>
    </div>
{% endblock content %}

movies/templates/movies/movie_detail.html
{% extends "base.html" %}

{% block content %}




        <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mx-auto mt-4 md:mt-0"><a href="{% url 'movies:movie-list' %}">Go Back to Movie List</a>
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </button>
    </head>
    <body>
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-4 mx-auto">
          <div class="lg:w-4/5 mx-auto flex flex-wrap">




            <!-- I changed all the img srcs to point to the aws bucket -->

            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://movie-review-files.s3.amazonaws.com/{{ movies.poster }}">
            <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
              <h2 class="text-sm title-font text-gray-500 tracking-widest">MOVIE NAME</h2>
              <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{ movies.title|upper }}</h1>
              <div class="flex mb-4">
                <span class="flex items-center">
                  <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-red-500" viewBox="0 0 24 24">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                  </svg>
                  <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-red-500" viewBox="0 0 24 24">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                  </svg>
                  <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-red-500" viewBox="0 0 24 24">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                  </svg>
                  <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-red-500" viewBox="0 0 24 24">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                  </svg>
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-red-500" viewBox="0 0 24 24">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
                  </svg>
                  <span class="text-gray-600 ml-3">{{ movies.rating }}</span>
                </span>
                <span class="flex ml-3 pl-3 py-2 border-l-2 border-gray-200 space-x-2s">
                  <a class="text-gray-500">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                      <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                    </svg>
                  </a>
                  <a class="text-gray-500">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                      <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                    </svg>
                  </a>
                  <a class="text-gray-500">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                      <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                    </svg>
                  </a>
                </span>
              </div>
              <p class="leading-relaxed">{{ movies.description }}</p>
              <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-100 mb-5">
                <div class="flex ml-0">
                  <span class="mr-3">{{ movies.reviews }} reviews</span>
                </div>
              </div>
              <div class="flex">
                <span class="title-font font-medium text-xl text-gray-900">Released: {{ movies.date_released }}</span>
                {% if request.user.is_organisor %}
                <button class="flex ml-auto text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded"><a href="{% url 'movies:movie-update' movies.pk %}">Update Movie</a></button>
                <button class="flex ml-2 text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded"><a href="{% url 'movies:movie-delete' movies.pk %}">Delete Movie</a></button>
                {% endif %}
                <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                  <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>


        <div class="container ml-3 px-5 py-4 mx-auto">
            <h1 class="text-gray-900 text-2xl heading-font font-medium mb-2">Reviews</h1>
        {% for review in reviews %}
          <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-7 border-gray-200 sm:flex-row flex-col">
            <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-2">{{ movies.title }}</h2>
              <p class="leading-relaxed text-base">{{ review.details }}</p>
              <span class="mr-3"><a class="mt-3 text-red-500 inline-flex items-center">{{review.author}}</a></span>
              <span class="mr-3">{{review.date_posted}}</span>
            </div>
          </div>
          {% empty %}
          <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-200 sm:flex-row flex-col">
            <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
              <h3 class="text-gray-900 text-lg title-font font-medium mb-2">No Reviews yet ...</h3>
              <a href="{% url 'movies:movie-review' movies.pk %}" class="mt-3 text-red-500 inline-flex items-center">Add a Review
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        {% endfor %}
        <a class="mt-0 text-red-500 inline-flex items-center">Add a Review
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
        </div>


        <div class="container mb-10 px-5 py-4 mx-auto">
          <h3><strong>Comments:</strong></h3>
          {% for comment in comments %}
          <div class="mb-3">
          <p class="leading-relaxed text-base">{{ comment.comment }}</p>
              <span class="mr-3"><a class="mt-3 text-red-500 inline-flex items-center">{{comment.author}}</a></span>
              <span class="mr-3">{{comment.date_posted}}</span>
              <a class="mt-3 text-red-500 inline-flex items-center">Learn More
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
              <hr/>
              {% empty %}
          <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-200 sm:flex-row flex-col">
            <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
              <h3 class="text-gray-900 text-lg title-font font-medium mb-2">No Comments yet ...</h3>
            </div>
          </div>
          </div>
          {% endfor %}
          <a href="{% url 'movies:comment-create' movies.pk %}" class="mt-3 text-red-500 inline-flex items-center">Add a Comment
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>

{% endblock content %}


movies/templates/movies/movie_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<h1 class="title-font sm:text-xl text-xl mb-4 font-medium text-gray-900">Update Movie: {{ movie.title }}</h1>


        <a href="/movies">Go back to Movies</a>
        <hr/>

    <!--  Movie Update Form  -->

    <div class="flex w-full justify-center items-end">
        <div class="relative mr-4 lg:w-full xl:w-1/2 w-2/4 md:w-full text-left">
          <label for="hero-field" class="leading-7 text-sm text-gray-600">Update {{ movie.title }}</label>

           <!-- i passed enctype here too -->
          <form class="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" value="Submit" class="inline-flex text-white bg-red-500 border-0 py-2 px-6 my-3 focus:outline-none hover:bg-red-600 rounded text-lg">Submit</button>
        </form>
        </div> 
      </div>


{% endblock content %}

movies/templates/movies/review_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}



<h1 class="text-center">Add a new Review for: {{ movie.title }}</h1>
    </head>
    <body>
        <a href="movies/movie_detail.html">Go back to {{ movie.title }}</a>
        <hr/>
    <div class="max-w-lg mx-auto">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="inline-flex text-white bg-red-500 border-0 py-2 px-6 my-3 focus:outline-none hover:bg-red-600 rounded text-lg" type="submit" value="Submit">
        </form>
    </div>
    </body>
</html>

{% endblock content %}