movies/urls.py
from django.urls import path
from .views import CommentCreateView, movie_create, MovieListView, MovieUpdateView, MovieDeleteView, ReviewCreateView, movie_detail

app_name = 'movies'

urlpatterns = [
    path('', MovieListView.as_view(), name='movie-list'),
    path('create/', movie_create, name='movie-create'),
    path('<int:pk>', movie_detail, name='movie-detail'),
    path('<int:pk>/update', MovieUpdateView.as_view(), name='movie-update'),
    path('<int:pk>/delete', MovieDeleteView.as_view(), name='movie-delete'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment-create'),
    path('<int:pk>/review/', ReviewCreateView.as_view(), name='movie-review'),
]

yem_reviews/urls.py
from os import name
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, LogoutView, 
    PasswordResetConfirmView, PasswordResetView, 
    PasswordResetDoneView, PasswordResetCompleteView)

    
from django.urls import path, include
from movies.views import LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('movies/', include('movies.urls', namespace='movies')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('signup/', SignupView.as_view(), name='signup'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Yem Reviews</title>
        <link rel="stylesheet" type="" href="{% static 'css/styles.css' %}">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body>
    {% include "navbar.html" %}
    <div class="">
    {% block content %}

    {% endblock content %}
    
    {% include "footer.html" %}
    </div>
    </body>
</html>

templates/footer.html


    <footer class="bg-dark dark:bg-gray-800">
        <div class="container mt-5 px-6 py-6 mx-auto">
            <div class="lg:flex">
                <div class="w-full -mx-6 lg:w-2/5">
                    <div class="px-6">
                        <div>
                            <a href="#" class="text-xl font-bold text-gray-800 dark:text-white hover:text-gray-700 dark:hover:text-gray-300">Yem Reviews</a>
                        </div>
                        
                        <p class="max-w-md mt-2 text-gray-500 dark:text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, nisi! Id.</p>
                        
                        <div class="flex mt-4 -mx-2">
                            <a href="#" class="mx-2 text-gray-700 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400" aria-label="Linkden">
                                <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                                    <path d="M444.17,32H70.28C49.85,32,32,46.7,32,66.89V441.61C32,461.91,49.85,480,70.28,480H444.06C464.6,480,480,461.79,480,441.61V66.89C480.12,46.7,464.6,32,444.17,32ZM170.87,405.43H106.69V205.88h64.18ZM141,175.54h-.46c-20.54,0-33.84-15.29-33.84-34.43,0-19.49,13.65-34.42,34.65-34.42s33.85,14.82,34.31,34.42C175.65,160.25,162.35,175.54,141,175.54ZM405.43,405.43H341.25V296.32c0-26.14-9.34-44-32.56-44-17.74,0-28.24,12-32.91,23.69-1.75,4.2-2.22,9.92-2.22,15.76V405.43H209.38V205.88h64.18v27.77c9.34-13.3,23.93-32.44,57.88-32.44,42.13,0,74,27.77,74,87.64Z"/>
                                </svg>
                            </a>

                            <a href="#" class="mx-2 text-gray-700 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400" aria-label="Facebook">
                                <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                                    <path d="M455.27,32H56.73A24.74,24.74,0,0,0,32,56.73V455.27A24.74,24.74,0,0,0,56.73,480H256V304H202.45V240H256V189c0-57.86,40.13-89.36,91.82-89.36,24.73,0,51.33,1.86,57.51,2.68v60.43H364.15c-28.12,0-33.48,13.3-33.48,32.9V240h67l-8.75,64H330.67V480h124.6A24.74,24.74,0,0,0,480,455.27V56.73A24.74,24.74,0,0,0,455.27,32Z"/>
                                </svg>
                            </a>

                            <a href="#" class="mx-2 text-gray-700 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400" aria-label="Twitter">
                                <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                                    <path d="M496,109.5a201.8,201.8,0,0,1-56.55,15.3,97.51,97.51,0,0,0,43.33-53.6,197.74,197.74,0,0,1-62.56,23.5A99.14,99.14,0,0,0,348.31,64c-54.42,0-98.46,43.4-98.46,96.9a93.21,93.21,0,0,0,2.54,22.1,280.7,280.7,0,0,1-203-101.3A95.69,95.69,0,0,0,36,130.4C36,164,53.53,193.7,80,211.1A97.5,97.5,0,0,1,35.22,199v1.2c0,47,34,86.1,79,95a100.76,100.76,0,0,1-25.94,3.4,94.38,94.38,0,0,1-18.51-1.8c12.51,38.5,48.92,66.5,92.05,67.3A199.59,199.59,0,0,1,39.5,405.6,203,203,0,0,1,16,404.2,278.68,278.68,0,0,0,166.74,448c181.36,0,280.44-147.7,280.44-275.8,0-4.2-.11-8.4-.31-12.5A198.48,198.48,0,0,0,496,109.5Z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="mt-6 lg:mt-0 lg:flex-1">
                    <div class="grid grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-4">
                        <div>
                            <h3 class="text-gray-700 uppercase dark:text-white">About</h3>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Company</a>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">community</a>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Careers</a>
                        </div>

                        <div>
                            <h3 class="text-gray-700 uppercase dark:text-white">Blog</h3>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Tec</a>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Music</a>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Videos</a>
                        </div>

                        <div>
                            <h3 class="text-gray-700 uppercase dark:text-white">Products</h3>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Mega cloud</a>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Aperion UI</a>
                            <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Meraki UI</a>
                        </div>

                        <div>
                            <h3 class="text-gray-700 uppercase dark:text-white">Contact</h3>
                            <span class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">+1 526 654 8965</span>
                            <span class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">example@email.com</span>
                        </div>
                    </div>
                </div>
            </div>

            <hr class="h-px my-6 bg-gray-300 border-none dark:bg-gray-700">

            <div>
                <p class="text-center text-gray-800 dark:text-white">© Brand 2020 - All rights reserved</p>
            </div>
        </div>
    </footer>

templates/landing.html
{% extends "base.html" %}

{% block content %}

<div class="container flex flex-col px-6 py-4 mx-auto space-y-6 lg:h-128 lg:py-16 lg:flex-row lg:items-center lg:space-x-6">
    <div class="flex flex-col items-center w-full lg:flex-row lg:w-1/2">
        <div class="flex justify-center order-2 mt-6 lg:mt-0 lg:space-y-3 lg:flex-col">
            <button class="w-3 h-3 mx-2 bg-red-500 rounded-full lg:mx-0 focus:outline-none"></button>
            <button class="w-3 h-3 mx-2 bg-gray-300 rounded-full lg:mx-0 focus:outline-none hover:bg-red-500"></button>
            <button class="w-3 h-3 mx-2 bg-gray-300 rounded-full lg:mx-0 focus:outline-none hover:bg-red-500"></button>
            <button class="w-3 h-3 mx-2 bg-gray-300 rounded-full lg:mx-0 focus:outline-none hover:bg-red-500"></button>
        </div>

        <div class="max-w-lg lg:mx-12 lg:order-2">
            <h1 class="text-3xl font-medium tracking-wide text-gray-800 dark:text-white text-center lg:text-4xl">Join the Largest Community of Movie Critics!</h1>
            <p class="mt-4 text-gray-600 dark:text-gray-300">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aut quia asperiores alias vero magnam recusandae adipisci ad vitae laudantium quod rem voluptatem eos accusantium cumque.</p>
            <div class="mt-6">
                <a href="{% url 'movies:movie-list' %}" class="block px-3 py-2 font-semibold text-center text-white transition-colors duration-200 transform bg-red-500 rounded-md lg:inline hover:bg-red-600">Go to Movie List</a>
            </div>
        </div>
    </div>

    <div class="flex items-center justify-center w-full h-96 lg:w-1/2">
        <img class="object-cover w-full h-full max-w-2xl rounded-md" src="https://i.redd.it/cfykincc7m671.jpg" alt="apple watch photo">
    </div>
</div>  

{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a href="{% url 'landing-page' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-red-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Yem Reviews</span>
      </a>
      <div class="collapse navbar-collapse" id="navbarToggle">
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
          <a href="{% url 'landing-page' %}" class="mr-5 hover:text-red-500">Home</a>
          <a href="{% url 'landing-page' %}" class="mr-5 hover:text-red-500">Categories</a>
          <a href="{% url 'landing-page' %}" class="mr-5 hover:text-red-500">Reviews</a>
          <a href="{% url 'landing-page' %}" class="mr-5 hover:text-red-500">News</a>
          <a href="{% url 'landing-page' %}" class="mr-5 hover:text-red-500">Shop
            <i class="fas fa-shopping-cart"></i>
          </a>
          {% if request.user.is_authenticated %}
            Logged in as: {{ request.user.username }}
            <a href="{% url 'logout' %}"class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mx-auto ml-5 md:mt-0">Logout</a>
          {% else %}
          <a href="{% url 'login' %}" class="mr-5 hover:text-red-500">Login</a>
          <a href="{% url 'signup' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mx-auto md:mt-0">Sign Up</a>
          {% endif %}
      </nav>
      </div> 
    </div>
  </header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>